---
title: "Classified Ads for Cars Dataset Analysis"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Connecting to HIVE runnubg on Hortonworks Sandbox VM

```
options( java.parameters = "-Xmx8g" )
library(rJava)
library(RJDBC)
 
cp = c("//d:/tools/apache-hive-1.2.2/lib/hive-jdbc-1.2.2-standalone.jar",
       "//d:/tools/hadoop-2.7.7/share/hadoop/common/hadoop-common-2.7.7.jar")
.jinit(classpath=cp) 
 
drv <- JDBC(driverClass = "org.apache.hive.jdbc.HiveDriver",
            classPath = "//d:/tools/apache-hive-1.2.2/lib/hive-jdbc-1.2.2-standalone.jar",
             identifier.quote="`")
 
conn <- dbConnect(drv, "jdbc:hive2://127.0.0.1:10000/used_cars", "maria_dev", "maria_dev")
```

## Discover the used_cars database


```{r message=FALSE, warning=FALSE, include=FALSE}
options( java.parameters = "-Xmx8g" )
library(rJava)
library(RJDBC)
 
cp = c("//d:/tools/apache-hive-1.2.2/lib/hive-jdbc-1.2.2-standalone.jar",
       "//d:/tools/hadoop-2.7.7/share/hadoop/common/hadoop-common-2.7.7.jar")
.jinit(classpath=cp) 
 
drv <- JDBC(driverClass = "org.apache.hive.jdbc.HiveDriver",
            classPath = "//d:/tools/apache-hive-1.2.2/lib/hive-jdbc-1.2.2-standalone.jar",
             identifier.quote="`")
 
conn <- dbConnect(drv, "jdbc:hive2://127.0.0.1:10000/used_cars", "maria_dev", "maria_dev")

```

## Discover the used_cars database

Events table size and head:

```{r eval=FALSE, include=FALSE}
# dbGetQuery(conn, "select count (*) from events")
```

```{r results='asis'}
library(xtable)
options(xtable.floating = TRUE)
options(xtable.timestamp = "")
options(xtable.comment = FALSE)

dbSendUpdate(conn, "USE used_cars")

cars <- dbGetQuery(conn, "select * from events limit 10")
colnames(cars) <- c(
  "maker", "model","mileage","year", "disp", "pwr", "body", "color", "stk", 
  "trans", "doors", "seats",  "fuel", "listed", "unlisted", "price")

print(xtable(cars), 
      caption="Classified Ads for Cars Dataset",
      type = "html", 
      include.rownames=FALSE, 
      caption.placement='top',
      html.table.attributes='align="left"')
```

```{r results='asis'}
library(knitr)
kable(cars, digits=2)
```


```{r}
descr <- dbGetQuery(conn, "describe events")
kable(descr)
```


```{r}
dbDisconnect(conn)
```
